version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/beepbot

permissions:
  - object: /home/ubuntu
    pattern: beepbot
    owner: ubuntu
    group: ubuntu
    mode: 771

  - object: /home/ubuntu/beepbot
    owner: ubuntu
    group: ubuntu
    mode: 771

hooks:
   BeforeInstall:
    - location: scripts/before.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/after.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu